You are given the following information, but you may prefer to do some research for yourself.

1 Jan 1900 was a Monday.
Thirty days has September,
April, June and November.
All the rest have thirty-one,
Saving February alone,
Which has twenty-eight, rain or shine.
And on leap years, twenty-nine.
A leap year occurs on any year evenly divisible by 4, but not on a century unless it is divisible by 400.
How many Sundays fell on the first of the month during the twentieth century (1 Jan 1901 to 31 Dec 2000)?

In [1]:
April = June = September = November = 30
January = March = May = July = August = October = December = 31
February = 28
February_leap = 29

In [20]:
#Could use prime numbers to count days of week?
#Could then divide by 17 to find any sundays?
Prime_numbers = 2,3,5,7,11,13,17
#Mon = 1, Sun = 17, etc..

In [26]:
#Double-check
January + February + March + April + May + June + July + August + September + October + November + December
Year = January + February + March + April + May + June + July + August + September + October + November + December

In [27]:
Year

365

In [37]:
January

31

In [92]:
#0 = sun, 1 = mon, 2 = tue, 3 = wed, 4 = thu, 5 = fri, 6 = sat
February%7

0

In [93]:
January%7
#this means 31 jan 1900 is a 3 i.e. a Wednesday?

3

In [94]:
Year%52
#This means that Dec 31 1900 is a Monday

1

In [77]:
#Designate months
Months = [January, February, March, April, May, June, July, August, September, October, November, December]

In [78]:
Months

[31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

In [66]:
#this is incorrect, adds an extra 1 to each first day.
#First_of_each_month = []
#for i in Months:
#    print(i)
#    First_of_each_month.append(i+1)

31
28
31
30
31
30
31
31
30
31
30
31


In [67]:
#First_of_each_month
#this gives first of month for feb to jan the following year
#actually this is wrong, it is adding 1 too many each time.

[32, 29, 32, 31, 32, 31, 32, 32, 31, 32, 31, 32]

In [76]:
Months

[31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31, 1]

In [79]:
First_of_the_months = Months

In [82]:
First_of_the_months

[1, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

In [81]:
#adds January 1 to start of list
First_of_the_months.insert(0,1)

In [43]:
import numpy as np

In [87]:
Day_in_year_first_of_month = np.cumsum(First_of_the_months)

In [88]:
Day_in_year_first_of_month

array([  1,  32,  60,  91, 121, 152, 182, 213, 244, 274, 305, 335, 366])

In [97]:
#if divisible by 0, the first of the month falls on a sunday.
for i in Day_in_year_first_of_month:
    if i%7 == 0:
        print(i)

91
182


In [71]:
String_months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

In [99]:
String_months

['Jan',
 'Feb',
 'Mar',
 'Apr',
 'May',
 'Jun',
 'Jul',
 'Aug',
 'Sep',
 'Oct',
 'Nov',
 'Dec']

In [114]:
Month_dict = dict.fromkeys(String_months,FoM_list)

In [116]:
Month_dict = zip(String_months,FoM_list)

In [118]:
Month_dictionary = dict(Month_dict)

In [119]:
Month_dictionary

{'Jan': 1,
 'Feb': 32,
 'Mar': 60,
 'Apr': 91,
 'May': 121,
 'Jun': 152,
 'Jul': 182,
 'Aug': 213,
 'Sep': 244,
 'Oct': 274,
 'Nov': 305,
 'Dec': 335}

In [129]:
#Now re-write this to print Month name
#Actually only need to count how many answers each year
#if divisible by 0, the first of the month falls on a sunday.
for i in Day_in_year_first_of_month:
    if i%7 == 0:
        print(i)
    

91
182


In [5]:
#now to iterate first of month over 100 years... paying attention to leap years.
#leap year calc
#this gives me all the years I am looking at:
#Months = [January, February, March, April, May, June, July, August, September, October, November, December]
#Months_leap = [January, February_leap, March, April, May, June, July, August, September, October, November, December]
#all_years = list(range(1901,2001))
#for year in all_years:
#    if year % 4 == 0:
#        year_length = January + February_leap + March + April + May + June + July + August + September + October + November + December
#        First_of_the_months = Months
#        
#        print(year)

1904
1908
1912
1916
1920
1924
1928
1932
1936
1940
1944
1948
1952
1956
1960
1964
1968
1972
1976
1980
1984
1988
1992
1996
2000


In [91]:
Century = (Months*3+Months_leap)*25

In [92]:
Century
#now add 1 Jan 1901 to the list
Century.insert(0,1)
#now cumsum the days over a century to get first of each month
import numpy as np
Century = np.cumsum(Century)
#remove the last entry which is Jan 1 2001
Century = np.delete(Century,-1)
print(Century)

[    1    32    60 ... 36434 36465 36495]


In [93]:
First_of_month_on_sunday = []
for i in Century:
    if i%7 == 1:
        First_of_month_on_sunday.append(i)

In [94]:
First_of_month_on_sunday

[1,
 274,
 456,
 547,
 974,
 1065,
 1156,
 1401,
 1674,
 1947,
 2192,
 2465,
 2801,
 2892,
 3074,
 3319,
 3347,
 3592,
 3865,
 4292,
 4474,
 4565,
 4992,
 5083,
 5265,
 5510,
 5692,
 5965,
 6210,
 6483,
 6665,
 6756,
 7092,
 7337,
 7365,
 7610,
 7883,
 8156,
 8401,
 8492,
 8583,
 9010,
 9101,
 9283,
 9528,
 9556,
 9801,
 9983,
 10228,
 10501,
 10683,
 10774,
 11201,
 11292,
 11383,
 11628,
 11901,
 12174,
 12419,
 12692,
 13028,
 13119,
 13301,
 13546,
 13574,
 13819,
 14092,
 14519,
 14701,
 14792,
 15219,
 15310,
 15492,
 15737,
 15919,
 16192,
 16437,
 16710,
 16892,
 16983,
 17319,
 17564,
 17592,
 17837,
 18110,
 18383,
 18628,
 18719,
 18810,
 19237,
 19328,
 19510,
 19755,
 19783,
 20028,
 20210,
 20455,
 20728,
 20910,
 21001,
 21428,
 21519,
 21610,
 21855,
 22128,
 22401,
 22646,
 22919,
 23255,
 23346,
 23528,
 23773,
 23801,
 24046,
 24319,
 24746,
 24928,
 25019,
 25446,
 25537,
 25719,
 25964,
 26146,
 26419,
 26664,
 26937,
 27119,
 27210,
 27546,
 27791,
 27819,
 28064,

In [95]:
len(First_of_month_on_sunday)
#i think this is the answer
#how to build a check?

171

In [64]:
#building a check
#document all of the sundays... then check which of those fall on first of month?
Jan_01_1901 = 
33663/7

4809.0

In [90]:
Century

array([    1,    32,    60, ..., 36434, 36465, 36495])

In [80]:
#this won't work because need unique keys
Century_dict = zip(String_months_Century,Century)

In [79]:
String_months_Century = String_months * 100

In [81]:
Century_dict = dict(Century_dict)

In [82]:
Century_dict

{'Jan': 36160,
 'Feb': 36191,
 'Mar': 36220,
 'Apr': 36251,
 'May': 36281,
 'Jun': 36312,
 'Jul': 36342,
 'Aug': 36373,
 'Sep': 36404,
 'Oct': 36434,
 'Nov': 36465,
 'Dec': 36495}